// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package rpc

import (
	"github.com/google/wire"
	"community-blogger/internal/app/userrpc/grpcserver"
	"community-blogger/internal/app/userrpc/repositories"
	"community-blogger/internal/pkg/config"
	"community-blogger/internal/pkg/log"
)

// Injectors from wire.go:

func CreateUserRpc(cf string, rpo repositories.UserRepository) (*UserSer, error) {
	viper, err := config.New(cf)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	userRPCServer := grpcserver.NewUserRPCServer(logger, viper, rpo)
	userSer := NewUserSer(logger, userRPCServer)
	return userSer, nil
}

// wire.go:

var testProviderSet = wire.NewSet(log.ProviderSet, config.ProviderSet, grpcserver.ProviderSet, ProviderSet)
