// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package services

import (
	"github.com/google/wire"
	"community-blogger/internal/app/home/repositories"
	"community-blogger/internal/pkg/config"
	"community-blogger/internal/pkg/log"
)

// Injectors from wire.go:

func CreateHomeService(cf string, rpo repositories.HomeRepository) (HomeService, error) {
	viper, err := config.New(cf)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	homeService := NewHomeService(logger, viper, rpo)
	return homeService, nil
}

// wire.go:

var testProviderSet = wire.NewSet(log.ProviderSet, config.ProviderSet, ProviderSet)
