// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package services

import (
	"community-blogger/internal/app/home/repositories"
	"community-blogger/internal/pkg/config"
	"community-blogger/internal/pkg/log"
	"community-blogger/internal/pkg/storages/minio"
	"community-blogger/internal/pkg/storages/oss"
	"community-blogger/internal/pkg/storages/qiniu"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateHomeService(cf string, rpo repositories.HomeRepository) (HomeService, error) {
	viper, err := config.New(cf)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	minioOptions, err := minio.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	client, err := minio.New(minioOptions)
	if err != nil {
		return nil, err
	}
	qiniuOptions, err := qiniu.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	formUploader, err := qiniu.New(qiniuOptions)
	if err != nil {
		return nil, err
	}
	ossOptions, err := oss.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	ossClient, err := oss.New(ossOptions)
	if err != nil {
		return nil, err
	}
	homeService := NewHomeService(logger, viper, rpo, client, formUploader, ossClient)
	return homeService, nil
}

// wire.go:

var testProviderSet = wire.NewSet(log.ProviderSet, config.ProviderSet, minio.ProviderSet, qiniu.ProviderSet, oss.ProviderSet, ProviderSet)
